apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-pod # Make sure this matches your pod labels
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
