apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kube
spec:
  selector:
    app: backend # Make sure this matches your pod labels
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
